import { useState } from 'react'
import { BedDouble, Bath, ChevronLeft, ChevronRight, Tv, Wifi, Droplets, ArrowUpRight } from 'lucide-react'
import { motion } from 'framer-motion'
import { rooms } from '../data/hotelData'

const icons = [BedDouble, Bath, Tv, Wifi, Droplets]
const ask = name => dispatchEvent(new CustomEvent('open-reservation',{detail:{room:name}}))
function RoomCarousel({room}){const [current,setCurrent]=useState(0),images=room.images||[room.image],go=step=>setCurrent(index=>(index+step+images.length)%images.length);return <div className="group/carousel relative overflow-hidden"><img className="h-64 w-full object-cover transition duration-500" src={images[current]} alt={`${room.name} — imagen ${current+1}`} loading="lazy"/>{images.length>1&&<><button onClick={()=>go(-1)} aria-label="Imagen anterior" className="absolute left-3 top-1/2 grid h-8 w-8 -translate-y-1/2 place-items-center rounded-full bg-black/45 text-white opacity-0 transition group-hover/carousel:opacity-100 hover:bg-black/70"><ChevronLeft size={18}/></button><button onClick={()=>go(1)} aria-label="Imagen siguiente" className="absolute right-3 top-1/2 grid h-8 w-8 -translate-y-1/2 place-items-center rounded-full bg-black/45 text-white opacity-0 transition group-hover/carousel:opacity-100 hover:bg-black/70"><ChevronRight size={18}/></button><div className="absolute bottom-3 left-1/2 flex -translate-x-1/2 gap-1.5">{images.map((_,index)=><button key={index} onClick={()=>setCurrent(index)} aria-label={`Ver imagen ${index+1}`} className={`h-1.5 rounded-full transition-all ${index===current?'w-5 bg-white':'w-1.5 bg-white/65'}`}/>)}</div></>}</div>}

export default function Rooms(){return <section id="habitaciones" className="bg-[#f3f0e9] py-24 lg:py-32"><div className="mx-auto max-w-7xl px-6"><div className="max-w-2xl"><p className="eyebrow">HABITACIONES</p><h2 className="title">Espacios pensados<br className="hidden sm:block"/> para descansar</h2><p className="copy max-w-xl">Elige la habitación que mejor acompaña tu viaje. Todas incluyen lo esencial para una estadía cómoda.</p></div><div className="mt-14 grid gap-5 md:grid-cols-3">{rooms.map((room,i)=><motion.article whileHover={{y:-5}} transition={{duration:.25}} className="group border border-[#d9d2c5] bg-[#faf8f4]" key={room.name}><RoomCarousel room={room}/><div className="p-6"><div className="flex items-start justify-between gap-4"><h3 className="font-sans text-xl font-bold leading-tight tracking-tight text-[#173d33]">{room.name}</h3><span className="text-[10px] font-bold tracking-[.18em] text-[#8b9a72]">0{i+1}</span></div><p className="mt-3 min-h-10 text-sm leading-6 text-[#607166]">{room.description}</p><div className="mt-5 flex items-end justify-between border-t border-[#ddd6ca] pt-4"><div><p className="text-[10px] font-bold tracking-[.16em] text-[#78856e]">DESDE</p><p className="mt-1 font-sans text-2xl font-bold tracking-tight text-[#173d33]">{room.price}<span className="ml-1 text-xs font-normal text-[#607166]">/ noche</span></p></div><span className="text-[10px] text-[#607166]">Tarifa referencial</span></div><div className="mt-5 border-t border-[#ddd6ca] pt-5"><p className="text-[10px] font-bold tracking-[.16em] text-[#78856e]">INCLUYE</p><ul className="mt-4 grid grid-cols-2 gap-x-3 gap-y-3">{room.features.map((feature,index)=>{const Icon=icons[index];return <li className="flex items-center gap-2 text-xs text-[#4d6257]" key={feature}><Icon size={14} strokeWidth={1.7}/>{feature}</li>})}</ul></div><button onClick={()=>ask(room.name)} className="mt-7 inline-flex items-center gap-3 border-b border-[#173d33] pb-1 text-xs font-bold text-[#173d33] transition hover:border-[#b08f5b] hover:text-[#9b7846]">Reservar <ArrowUpRight size={15}/></button></div></motion.article>)}</div></div></section>}
